### ISSUE TITLE
Real Columns Grid

### ISSUE THREAD

**Issue by vitor-mendrone-deel** [Fastcommerce/Wave#1]
Utilizar grids reais em vez de padding grids permite maior flexibilidade nos layouts e HTML mais limpo. 

http://imgur.com/a/OWyOQ

Em resumo é preciso alterar as grids de: 

``` css
[class*='col-small-']{
    float: left;
    padding: 0px 10px 5px 10px;
}
```

Para: 

``` css
[class*='col-small-']{
    float: left;
    margin-left: 5%;
}
```

Lembrando que o first-child não deve ter a margin-left.
